
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# (PART\*) Cluster 101 {-}

# What is a Cluster?

A computing cluster is a set of many computers networked together. Because there are many computers working together, the network is able to handle computationally expensive tasks, like genome assemblies or advanced algorithms. Imagine you're building a house. It would take a long time by yourself! It's much better to have many builders working together.

Now that we have a team of workers, the next challenge is task management. A home construction team will need a manager to help delegate tasks. Similarly, the computing cluster uses management software to prioritize tasks, delegate workers (resources), and check on progress. The Fred Hutch cluster uses a common management and scheduling tool called [Slurm](https://slurm.schedmd.com/overview.html).

How is the cluster different from a laptop or desktop? First, you might use an operating system like Windows or MacOS. The Fred Hutch server is a Linux system. Second, because many people use the cluster for many tasks, there isn't a central screen and keyboard. You access the cluster remotely from your computer! We will talk more about how to connect to the cluster in a [following chapter](#terminal).

<div class = "dictionary">
**Computing cluster**  
  
A set of computers networked together to perform large tasks.
</div>

# Account Setup

You will need an account to log in to the cluster. This ensures that data stays protected.

## Check your HutchNet ID

A [HutchNet ID](https://centernet.fredhutch.org/cn/u/center-it/help-desk.html) is the standard login you receive when you start working at the Hutch or are an official affiliate. You can use it to login to most resources at the Center (Desktop Computer, Employee Self Service, VPN, Webmail) and our Scientific Computing systems. 

For example:  

- my email is `jsmith3@fredhutch.org`.  
- my HutchNet ID is `jsmith3`.  

<div class = "notice">
If one of your collaborators requires access to the Fred Hutch network you can submit a [non-employee action form](https://centernet.fredhutch.org/cn/f/hr/lcex/non-employee-action-form.html). Non-employee is a generic administrative term for affiliates, students, contractors, etc.
</div>

## Contacting the SciComp Team

To use Scientific Computing clusters at Hutch, your HutchNet ID must be associated with a PI account. 

The Scientific Computing Team (SciComp) tries to set some users up ahead of time. However, not everyone is set up automatically. Please fill out [this Account Setup Form](https://forms.gle/5ct8mQCeBD7LUt6S7) and we will ensure you are set up correctly!

<div class = "warning">
Errors similar to “Invalid account or account/partition” typically indicate that the account hasn’t been set up by SciComp. This is a quick fix if you use the form above.
</div>

Now, let's set up our Terminal!

# Terminal Setup {#terminal}

The next step is getting familiar with your Terminal. This is your portal to the cluster.

## What is a terminal?

The Terminal is a [command line interface](https://www.codecademy.com/article/command-line-interface). In other words, the Terminal is a software application that allows you to issue commands directly to your laptop or desktop computer. The Terminal is very useful because it allows you to run commands that don't have a graphical user interface (GUI). It can also connect you to computer networks, such as the Fred Hutch cluster! The Terminal setup is different depending on your operating system. Jump to either [Windows](#windows) or [MacOS / Linux](#mac-or-linux) sections below.

<div class = "terminal">
"Terminal" used to be synonymous with "computer". With the creation of operating systems like Windows and MacOS, computers became much easier to use and exploded in popularity! Your colleagues are almost always referring to the command line application when they say "Terminal".
</div>

## Windows Setup {#windows}

You will need to install a Terminal application called **PuTTY** to connect to the Fred Hutch Cluster.
  
1. [Click here to download PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)  
1. Double-click on the downloaded file to start the installation and Setup Wizard.
1. Once the installer is finished, click on the PuTTY application to make sure a window opens. It will look like this:
   
[SCREENSHOT]

## Mac/Linux Setup {#mac-or-linux}

Mac and Linux machines already come with a Terminal installed. 

**Mac Setup**

1. Go to Finder > Applications > Utilities > Terminal and double-click. 
1. Your Terminal should look like this:
    
[SCREENSHOT]
    
**Linux Setup**

1. Press ctrl + alt + T. Your open Terminal window should look like this:

[SCREENSHOT]

# Logging In

Now that you have your Terminal application ready, you want to connect to the cluster. You will do this using a method called [SSH](https://www.ssh.com/academy/ssh/protocol), which stands for "Secure Shell".

## What is `SSH`?

SSH is a secure way to remotely connect to another computer or network of computers. In other words, SSH helps us protect your data and the data on the Fred Hutch cluster through authentication.

## Logging in via `SSH`

1. You will need to connect to the [Fred Hutch VPN](https://centernet.fredhutch.org/cn/u/center-it/help-desk/vpn.html). This is the first layer of security.  
1. Next you will type the following commands:  
    ```
    Commands
    ```
    
1. Enter your password, No`*` or symbols will show up, so type it in carefully!
1. You are now logged in! You can type "yes" when you see a message that looks like this:
    ```
    Message
    ```
  
Congratulations! You are now logged in to the Fred Hutch cluster!

# Tour your space

# Submit your first job

# Interactive cluster

# File upload and download

## Globus


