
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

_Please note that this course is under developmnent and these credits are subject to change!_

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor|[Ava Hoffman]|
|Content Authors|The Fred Hutch SciComp Team|
|Content Editors|Amy Paguirigan|
|Content Reviewers|Elizabeth Humphries, [Candace Savonen], [Carrie Wright]|
|Content Consultants|The Fred Hutch SciComp Team|
|**Technical**||
|Course Publishing Engineer|[Ava Hoffman]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal]) [Candace Savonen], [John Muschelli], [Carrie Wright]|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[Ava Hoffman]: https://www.avahoffman.com/
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits
-->
