# (PART\*) Appendix {-}

# Where to get help {#help}

We want to help! Here are some ways you can get help for your work on the cluster.

## Submit a Ticket {-}

Submitting a good ticket helps the SciComp Team address your needs quickly and efficiently. We suggest you submit the following in a ticket:

1.  
1.  
1.  

## Visit the SciWiki {-}

The SciWiki [Scientific Computing page](https://sciwiki.fredhutch.org/scicomputing/comp_index/) is full of useful tips and guides.

# Provide Feedback {#feedback}

Please submit an issue at our [GitHub repository](https://github.com/fhdsl/FH_Cluster_Guide/issues/new). You can also click the edit button on the top of the page in question.

# FAQ {-}

Here are some issues you might encounter.

## How can I manually install PuTTY? {#manual-putty}

<details><summary>Click to view steps</summary><p>

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "appendix/_manual_PuTTY_install.Rmd",
  repo_name = "fhdsl/FH_Cluster_Guide"
)
```

</p></details>

# Troubleshooting Help {-}

Here are some issues you might encounter.

### `ssh: Could not resolve hostname rhino: nodename nor servname provided, or not known` {-}

<details><summary>Click to view steps</summary><p>

This error means that your computer is having trouble connecting to rhino. Ensure one of the following is true:

1. You are connected to the Fred Hutch WiFi network on campus.
1. You are connected to the Fred Hutch VPN
1. You are plugged into an ethernet cable on campus that taps into the Fred Hutch network. Note that not all ethernet wall jacks have this capability, so try another jack if you are having trouble. Please email the IT helpdesk and include your office number and the number on the jack if you find a jack that isn't working.

</p></details>

### `ssh: connect to host rhino port 22: Undefined error: 0` {-}

<details><summary>Click to view steps</summary><p>

This likely indicates a disruption to your internet connection and/or VPN. Ensure you are connected to the internet and connected to the Fred Hutch network on campus or the VPN.

</p></details>
