---
title: "FH Cluster Guide"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/favicon.ico
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), "bookdown", "knitr", "rmarkdown"
), "packages.bib")
```

# About this Course {-}

The Fred Hutch maintains a high performance computing cluster specifically to support research work that requires more intensive computing than your average desktop computer can handle.  This resource is supported by a group in IT called Scientific Computing, and this course was developed by the Fred Hutch Data Science Lab in collaboration with them.  

Our goal for this course is to get you running on the Fred Hutch cluster quickly and efficiently with this quick-start guide.  This course is intended for anyone who may benefit from using the cluster, as well as staff new to the Hutch who may have used a cluster at another institution.  

As a wise Drivers' Ed instructor once said, **you need to go slow to go fast**! 

In this short course, you'll invest a bit of time now to save you time and frustration down the road. Follow along at **any time on your own schedule**. We hope that the following modules will help you take advantage of the powerful resources the Fred Hutch has to offer!

<!-- we would rather folks waste computing resources than not use it at all! -->
